version: "2"

# need to create our own network, so when we scan our repos we can connect to these containers by name from the scanner container.
networks:
  lan:
    driver: bridge

services:
  sonarqube:
    image: sonarqube:7.9-community
    container_name: sonarqube
    hostname: sonarqube
    networks:
      - lan
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_postgres:5432/sonarqube
    logging:
      driver: "json-file"

  sonarqube_postgres:
    image: postgres:11.5-alpine
    container_name: sonarqube_postgres
    hostname: sonarqube_postgres
    networks:
      - lan
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    logging:
      driver: "json-file"
