version: "2"
networks:
  lan:
    driver: bridge

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    networks:
      - lan
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_postgres:5432/sonarqube
    logging:
      driver: "json-file"
  postgres:
    image: postgres:10.3-alpine
    container_name: sonarqube_postgres
    hostname: sonarqube_postgres
    networks:
      - lan
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    logging:
      driver: "json-file"
